const path = require('path');
const ejs = require('ejs');

const translations = {
  ar: {
    reportTitle: 'تقرير صندوق الفرح',
    event: 'المناسبة',
    groomName: 'العريس',
    eventDate: 'تاريخ الحفل',
    generatedAt: 'تاريخ الإصدار',
    contributionsSection: 'المساهمات',
    expensesSection: 'المصروفات',
    summarySection: 'الملخص',
    friendName: 'اسم الصديق',
    amountPaid: 'المبلغ المدفوع',
    expenseName: 'البند',
    expenseAmount: 'المبلغ',
    expenseDate: 'التاريخ',
    totalCollected: 'إجمالي المجموع',
    totalSpent: 'إجمالي المصروف',
    balance: 'الرصيد المتبقي',
    total: 'المجموع',
    currency: 'MRU',
    status: { active: 'نشط', closed: 'مغلق' },
    notes: 'ملاحظات',
  },
  fr: {
    reportTitle: 'Rapport du Fonds de Mariage',
    event: 'Événement',
    groomName: 'Marié',
    eventDate: 'Date de l\'événement',
    generatedAt: 'Généré le',
    contributionsSection: 'Contributions',
    expensesSection: 'Dépenses',
    summarySection: 'Résumé',
    friendName: 'Nom de l\'ami',
    amountPaid: 'Montant payé',
    expenseName: 'Libellé',
    expenseAmount: 'Montant',
    expenseDate: 'Date',
    totalCollected: 'Total collecté',
    totalSpent: 'Total dépensé',
    balance: 'Solde restant',
    total: 'Total',
    currency: 'MRU',
    status: { active: 'Actif', closed: 'Clôturé' },
    notes: 'Notes',
  },
  en: {
    reportTitle: 'Wedding Fund Report',
    event: 'Event',
    groomName: 'Groom',
    eventDate: 'Event Date',
    generatedAt: 'Generated At',
    contributionsSection: 'Contributions',
    expensesSection: 'Expenses',
    summarySection: 'Summary',
    friendName: 'Friend Name',
    amountPaid: 'Amount Paid',
    expenseName: 'Expense',
    expenseAmount: 'Amount',
    expenseDate: 'Date & Time',
    totalCollected: 'Total Collected',
    totalSpent: 'Total Spent',
    balance: 'Remaining Balance',
    total: 'Total',
    currency: 'MRU',
    status: { active: 'Active', closed: 'Closed' },
    notes: 'Notes',
  }
};

const MONTHS = {
  ar: ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'],
  fr: ['Janvier','Février','Mars','Avril','Mai','Juin','Juillet','Août','Septembre','Octobre','Novembre','Décembre'],
  en: ['January','February','March','April','May','June','July','August','September','October','November','December'],
};

function pad(n) { return String(n).padStart(2, '0'); }

function formatMRU(amount, lang) {
  const rounded = Math.round(amount);
  if (lang === 'fr') {
    const str = rounded.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ' ');
    return `${str} MRU`;
  } else {
    const str = rounded.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
    return `${str} MRU`;
  }
}

function formatDatetime(date, lang) {
  const d = new Date(date);
  const day = pad(d.getDate());
  const month = pad(d.getMonth() + 1);
  const year = d.getFullYear();
  const hour = pad(d.getHours());
  const min = pad(d.getMinutes());
  if (lang === 'ar') return `${day}/${month}/${year} - ${hour}:${min}`;
  if (lang === 'fr') return `${day}/${month}/${year} ${hour}:${min}`;
  return `${month}/${day}/${year} ${hour}:${min}`;
}

function formatDate(date, lang) {
  const d = new Date(date);
  const day = d.getDate();
  const monthName = MONTHS[lang][d.getMonth()];
  const year = d.getFullYear();
  return `${day} ${monthName} ${year}`;
}

async function generateReport(res, eventData, contributions, expenses, lang = 'en') {
  const t = translations[lang] || translations.en;
  const isRTL = lang === 'ar';

  const totalCollected = contributions.reduce((s, c) => s + c.amount, 0);
  const totalSpent = expenses.reduce((s, e) => s + e.amount, 0);
  const balance = totalCollected - totalSpent;

  const generatedByText = lang === 'ar'
    ? 'تم الإنشاء بواسطة مدير صندوق الأعراس'
    : lang === 'fr'
    ? 'Généré par Wedding Fund Manager'
    : 'Generated by Wedding Fund Manager';

  // Gather data for template
  const templateData = {
    eventData,
    contributions,
    expenses,
    lang,
    isRTL,
    t,
    totalCollected,
    totalSpent,
    balance,
    generatedByText,
    dateLine: formatDate(eventData.eventDate, lang),
    genLine: formatDatetime(new Date(), lang),
    formatMRU,
    formatDatetime,
    formatDate
  };

  const templatePath = path.join(__dirname, '../templates/report.ejs');
  const html = await ejs.renderFile(templatePath, templateData);

  const puppeteerCore = await import('puppeteer-core');
  let executablePath, browserArgs;

  if (process.env.VERCEL || process.env.AWS_LAMBDA_FUNCTION_NAME) {
    const chromium = require('@sparticuz/chromium');
    chromium.setGraphicsMode = false;
    executablePath = await chromium.executablePath();
    browserArgs = chromium.args;
  } else {
    executablePath =
      process.env.CHROME_EXECUTABLE_PATH ||
      '/usr/bin/google-chrome' ||
      '/usr/bin/chromium-browser' ||
      '/usr/bin/chromium';
    browserArgs = ['--no-sandbox', '--disable-setuid-sandbox'];
  }

  const browser = await puppeteerCore.launch({
    executablePath,
    args: browserArgs,
    headless: true,
  });

  const page = await browser.newPage();
  await page.setContent(html, { waitUntil: 'networkidle0', timeout: 15000 });

  const pdfRaw = await page.pdf({
    format: 'A4',
    printBackground: true,
    margin: {
      top: '50px',
      right: '50px',
      bottom: '50px',
      left: '50px'
    }
  });

  await browser.close();

  const pdfBuffer = Buffer.from(pdfRaw);

  if (pdfBuffer.length === 0) {
    throw new Error('PDF buffer is empty');
  }

  const filename = `report-${eventData._id}-${lang}.pdf`;
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
  res.setHeader('X-PDF-Size', String(pdfBuffer.length));
  res.send(pdfBuffer);
}

module.exports = { generateReport };
